name: Alimentares
favicon: null
layout_spectrum: 0.5872579300776124
typography_spectrum: 0.14505884959362447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.41395264002494514
  lightness: 0.3858571716118604
  saturation: 0.9713287623599172
  rhythmicContrast: 0.16324978624470532
purpose: []
